#!/bin/bash

# this is a simple config for herbstluftwm

hc() {
    cmds="$cmds , $@"
}

hc emit_hook reload

# colors
hc set frame_border_normal_color  '#000000'
hc set frame_border_active_color  '#FFFFFF'
hc set frame_bg_normal_color      '#222222'
hc set frame_bg_active_color      '#565656'
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#9fbc00'

# transparity
hc set frame_bg_transparent 1
hc set frame_active_opacity 0
hc set frame_normal_opacity 0

# gaps
hc set always_show_frame 0
hc set frame_gap 0
hc set frame_padding 0
hc set frame_border_width 0

hc set window_gap 0
hc set window_border_width 2
hc set window_border_inner_width 0

hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0

# layouts
hc set default_frame_layout 2

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# rules
hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class='Gvim' focus=on
hc rule title~'Figure.*' index=/0 focus=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)|st|st-256color' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on

#hc set tree_style '╾│ ├└╼─┐'
hc set tree_style "-| |'--"

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
hc detect_monitors

# execute all above settings
herbstclient chain $cmds&

# create all keybindings
keybinds=~/.config/herbstluftwm/keybindings
$keybinds

# unlock, just to be sure
herbstclient unlock

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done
